version: '3.8'

services:
  backend:
    build: ./apps/backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./apps/backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./apps/frontend
    container_name: frontend
    command: flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0
    volumes:
      - ./apps/frontend:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
